version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build-dev:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy to dev env
          command: ./node_modules/.bin/firebase deploy --toekn "$FIREBASE_TOKEN"
  build-staging:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: build
          command: npm run build
  build-prod:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: build
          command: npm run build

workflows:
  version: 2
  sample: 
    jobs:
      - build-dev:
          filters:
            branches:
              only: develop
      - build-staging:
          filters:
            branches:
              only: main
      - build-prod:
          filters:
            branches:
              only: main

